# Generated by Django 3.2.5 on 2022-04-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
