# Generated by Django 3.2.5 on 2022-04-24 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSystem', '0002_alter_comments_comment_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'managed': False},
        ),
    ]
