# Generated by Django 3.2.5 on 2022-04-24 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSystem', '0003_alter_comments_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comments',
            table='comments',
        ),
    ]
