# Generated by Django 4.0 on 2022-05-05 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSystem', '0004_alter_comments_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderlist',
            table='order_list',
        ),
    ]
