# Generated by Django 4.0 on 2022-05-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSystem', '0005_alter_orderlist_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('mark_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('marks', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
            options={
                'db_table': 'mark',
                'managed': False,
            },
        ),
    ]
