# Generated by Django 3.2.5 on 2022-05-30 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminSystem', '0006_mark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': '普通管理员', 'verbose_name_plural': '普通管理员'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False, 'verbose_name': '普通用户', 'verbose_name_plural': '普通用户'},
        ),
    ]
